#!/bin/bash
# PICTURE=/tmp/i3lock.png
# SCREENSHOT="scrot $PICTURE"

# BLUR="5x6"

# $SCREENSHOT
# convert $PICTURE -blur $BLUR $PICTURE
# i3lock -i $PICTURE
# rm $PICTURE


#Thanks to lokesh-krishna for this lock screen
IMAGE=$HOME/.config/i3lock/lock-wallpaper.png

i3lock --nofork                 	\
    --ignore-empty-password		\
    \
    --indicator				\
    --ind-pos='3720:900' \
    --radius=90\
    --ring-width=20 \
    --inside-color=FF7823 \
    --line-uses-inside \
    --ring-color=FACF1C \
    --ringver-color=000000\
    --ringwrong-color=bf616a		\
    --bshl-color=5e81ac			\
    --keyhl-color=a3be8c			\
    \
    --clock				\
    --time-color=eceff4ff		\
    --time-str="%I:%M %p"		\
    --time-font="Calvin and Hobbes"	\
    --time-size=150			\
    --time-pos="4500:1300"		\
    --time-color=2e3440ff		\
    \
    --date-color=d8dee9ff		\
    --date-str="%A, %d %B"		\
    --date-color=2e3440ff		\
    --date-font="Calvin and Hobbes"	\
    --date-size=95			\
    --date-pos="4500:1425"	\
    \
    --verif-font="Calvin and Hobbes"	\
    --verif-size=150			\
    --verif-text="Welcome home!"		\
    --wrong-font="Calvin and Hobbes"	\
    --wrong-size=150			\
    --wrong-text="No Entry!"		\
    \
    --image=$IMAGE \
    --fill


